name: specbolt CI
on: [ push ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        build_type: [ Debug, RelWithDebInfo ]
    steps:
      - uses: actions/checkout@v4
      - name: setup X11
        run: |
          sudo apt-get install -y libx11-dev libxext-dev
      - name: Setup cmake
        uses: jwlawson/actions-setup-cmake@v2
        with:
          cmake-version: '3.30.x'
      - name: Install ninja-build tool
        uses: seanmiddleditch/gha-setup-ninja@v5
      - name: install clang
        run: |
          wget https://apt.llvm.org/llvm.sh
          chmod +x llvm.sh
          sudo ./llvm.sh 19
      - name: Build
        run: |
          mkdir build
          env CC=clang CXX=clang++ cmake -S . -B build -G Ninja -DCMAKE_BUILD_TYPE=${{ matrix.build_type }}
          cmake --build build
          cmake --build build --target test
